### ISSUE TITLE
New calibration from Val mocap to Val torso

### ISSUE THREAD

**Issue by a-price** [UM-ARM-Lab/lightweight_vicon_bridge#11]
Here are the results we got from calibrating Val's torso with the Vicon markers. I'm not sold on the accuracy, due to all the backlash in the system, but it may be better than what we had.

```
parent_frame_id: mocap_ValOnHusky_ValOnHusky
frame_id: val_root
```

```
pose:
  position:
    x: -0.0318574064543
    y: -0.0313317285606
    z: -0.0304785243467
  orientation:
    x: -0.0179397003967
    y: 0.0105275909015
    z: -0.708665575372
    w: 0.70523786006
```
